### ISSUE TITLE
Misskey 11.0.0がビルドできない

### ISSUE THREAD

**Issue by khws4v1** [khws4v1/misskey#4]
Misskey 11.0.0のDockerがビルドできない問題

ログ:
```
[13:38:17] '<anonymous>' errored after 287 ms
[13:38:17] Error: File not found with singular glob: /misskey/build/Release/crypto_key.node (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/misskey/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:285:13)
    at Glob.emit (events.js:197:13)
    at Glob.EventEmitter.emit (domain.js:439:20)
    at Glob._finish (/misskey/node_modules/glob/glob.js:197:8)
    at done (/misskey/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/misskey/node_modules/glob/glob.js:688:12)
    at /misskey/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/misskey/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/misskey/node_modules/glob/glob.js:764:12)
[13:38:17] 'build:copy' errored after 606 ms
[13:38:17] 'build' errored after 612 ms
[13:38:17] The following tasks did not complete: build:ts, build:client, doc, build:copy:views, build:client:script, build:client:styles, copy:client
[13:38:17] Did you forget to signal async completion?
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

**Comment by khws4v1** [comment]
原因:

crypto_key.ccがいらないので、ビルドしないようにしてた:
https://github.com/syuilo/misskey/pull/4644/files#diff-3254677a7917c6c01f55212f86c57fbf

しかし、なぜかbinding.gypが復活していたので無を参照してしまっていた。
https://github.com/syuilo/misskey/commit/9b594880c88b0fe7ba14df263cc571e507f50bd6#diff-21e418851ae48f9b11907837add9e39a

**Comment by khws4v1** [comment]
多分直った:
https://github.com/syuilo/misskey/commit/a1f7b009810cd94c3d43752ae035d4ff123dd4de

**Comment by khws4v1** [comment]
ビルドが通ることを確認したのでクローズします。
